[package]
name = "day_5"
version = "0.0.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
colored = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true }
